#!/usr/bin/env bash
# PRaww+ — full update script
# Usage (Oracle VPS):  bash update.sh [branch]
# Usage (Replit):      bash update.sh --local     (skip git pull, just rebuild)
#
# Environment variables:
#   SERVICE_NAME   systemd unit name  (default: prawwplus)
#   APP_DIR        repo root          (default: directory of this script)
#   ENV_FILE       path to .env file  (default: /home/ubuntu/PRawwPlus/.env)
#   WRAPPER        path to startup wrapper script

set -euo pipefail

BRANCH="${1:-master}"
LOCAL_ONLY=false
if [[ "${1:-}" == "--local" ]]; then LOCAL_ONLY=true; fi

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="${SERVICE_NAME:-prawwplus}"
ENV_FILE="${ENV_FILE:-/home/ubuntu/PRawwPlus/.env}"
WRAPPER="${WRAPPER:-/home/ubuntu/start-prawwplus.sh}"

log() { echo "[update] $*"; }
err() { echo "[update] ERROR: $*" >&2; exit 1; }

# ── 1. Pull latest code ───────────────────────────────────────────────────────
if [[ "$LOCAL_ONLY" == false ]]; then
  log "Fetching origin/$BRANCH ..."
  git -C "$APP_DIR" fetch origin
  log "Resetting to origin/$BRANCH ..."
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
  log "Code is now at: $(git -C "$APP_DIR" log --oneline -1)"

  # ── Environment guard — refuse to deploy with a broken .env ─────────────────
  if ! grep -q "SESSION_SECRET" "$ENV_FILE" 2>/dev/null; then
    err ".env missing SESSION_SECRET — aborting ($ENV_FILE)"
  fi
  if ! grep -q "FREESWITCH_ESL_PASSWORD" "$ENV_FILE" 2>/dev/null; then
    err ".env missing FREESWITCH_ESL_PASSWORD — aborting ($ENV_FILE)"
  fi
  log "Environment guard passed (.env has SESSION_SECRET and FREESWITCH_ESL_PASSWORD)"
fi

# ── 2. Install / update dependencies ─────────────────────────────────────────
log "Installing dependencies (pnpm)..."
cd "$APP_DIR"
pnpm install --frozen-lockfile

# ── 3. Build shared libraries ─────────────────────────────────────────────────
log "Building shared libraries..."
pnpm --filter './lib/**' run build

# ── 4. Build React frontend ───────────────────────────────────────────────────
log "Building frontend (Vite)..."
pnpm --filter @workspace/prawwplus run build

# ── 5. Write / refresh startup wrapper ───────────────────────────────────────
# The wrapper uses Node.js to parse .env safely — bash `source` breaks on
# unquoted values containing angle brackets, spaces, or other special chars.
log "Writing startup wrapper ($WRAPPER) ..."
cat > "$WRAPPER" << WRAPEOF
#!/usr/bin/env bash
# PRaww+ startup wrapper — auto-generated by update.sh
# Loads .env via Node.js so special characters in values are handled safely.
ENV_FILE=$ENV_FILE

eval "\$(node -e "
const fs = require('fs');
const lines = fs.readFileSync('\$ENV_FILE', 'utf8').split('\n');
for (const line of lines) {
  const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=([\\\s\\\S]*)/);
  if (!m) continue;
  let [, key, val] = m;
  val = val.replace(/^([\\\"'])([\\s\\S]*)\\1\$/, '\\$2');
  process.stdout.write('export ' + key + '=' + JSON.stringify(val) + '\n');
}
")"

export NODE_ENV=production
export PORT=5000

cd $APP_DIR
exec pnpm --filter @workspace/api-server run start
WRAPEOF
chmod +x "$WRAPPER"
log "Startup wrapper written."

# ── 6. Restart process manager ───────────────────────────────────────────────
if [[ "$LOCAL_ONLY" == true ]]; then
  log "Local mode — skipping process-manager restart (use the Replit workflow)."
elif command -v systemctl &>/dev/null && systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
  log "Restarting systemd service '$SERVICE_NAME'..."
  sudo systemctl restart "$SERVICE_NAME"
  sleep 2
  systemctl is-active --quiet "$SERVICE_NAME" && log "Service is running." \
    || err "Service failed to start — check: journalctl -u $SERVICE_NAME -n 50"
elif command -v pm2 &>/dev/null; then
  log "Deploying via pm2 ($SERVICE_NAME) using wrapper $WRAPPER ..."
  pm2 delete "$SERVICE_NAME" 2>/dev/null || true
  pm2 start "$WRAPPER" --name "$SERVICE_NAME" --interpreter bash
  pm2 save
  log "pm2 reports: $(pm2 list | grep "$SERVICE_NAME" | awk '{print $10}')"
else
  log "WARNING: No systemd service or pm2 found. Run manually:"
  log "  bash $WRAPPER"
fi

log "=== PRaww+ update complete ==="
git -C "$APP_DIR" log --oneline -1
