#!/usr/bin/env bash
# =============================================================================
# PRaww+ — Coturn TURN/STUN Server Setup
# =============================================================================
# Run this on your Ubuntu/Debian VPS (same or separate machine from FreeSWITCH).
#
# What this script does:
#   1. Installs Coturn
#   2. Generates a strong TURN_SECRET (or uses your existing one)
#   3. Writes /etc/turnserver.conf with all required settings
#   4. Opens firewall ports (ufw)
#   5. Enables and starts the coturn systemd service
#   6. Prints the env vars to add to your PRaww+ .env
#
# Usage:
#   chmod +x deploy/coturn-setup.sh
#   sudo ./deploy/coturn-setup.sh
#
# Required env vars (set before running or the script will prompt):
#   TURN_DOMAIN   — public hostname/IP for the TURN server  e.g. turn.praww.co.za
#   TURN_SECRET   — shared HMAC secret (generated if blank)
#   PUBLIC_IP     — VPS public IP (auto-detected if blank)
#
# Optional:
#   RELAY_MIN_PORT  — relay UDP port range start  (default: 49152)
#   RELAY_MAX_PORT  — relay UDP port range end    (default: 65535)
#   TLS_CERT        — path to TLS cert PEM (e.g. /etc/letsencrypt/live/.../fullchain.pem)
#   TLS_KEY         — path to TLS key PEM  (e.g. /etc/letsencrypt/live/.../privkey.pem)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo $0"

# ── Collect required values ────────────────────────────────────────────────────

if [[ -z "${TURN_DOMAIN:-}" ]]; then
  read -rp "TURN server hostname (e.g. turn.praww.co.za or your VPS IP): " TURN_DOMAIN
fi
[[ -z "$TURN_DOMAIN" ]] && error "TURN_DOMAIN is required"

if [[ -z "${PUBLIC_IP:-}" ]]; then
  PUBLIC_IP=$(curl -sf https://api4.my-ip.io/ip 2>/dev/null || curl -sf https://ipv4.icanhazip.com 2>/dev/null || true)
  if [[ -z "$PUBLIC_IP" ]]; then
    read -rp "VPS public IP address: " PUBLIC_IP
  fi
fi
[[ -z "$PUBLIC_IP" ]] && error "PUBLIC_IP is required"

if [[ -z "${TURN_SECRET:-}" ]]; then
  TURN_SECRET=$(openssl rand -hex 32)
  info "Generated TURN_SECRET: $TURN_SECRET"
fi

RELAY_MIN_PORT=${RELAY_MIN_PORT:-49152}
RELAY_MAX_PORT=${RELAY_MAX_PORT:-65535}

echo ""
info "Configuration:"
echo "  TURN_DOMAIN   = $TURN_DOMAIN"
echo "  PUBLIC_IP     = $PUBLIC_IP"
echo "  TURN_SECRET   = [hidden]"
echo "  Relay ports   = $RELAY_MIN_PORT–$RELAY_MAX_PORT"
echo "  TLS cert      = ${TLS_CERT:-[none — TLS 5349 will use self-signed]}"
echo ""

# ── Install Coturn ─────────────────────────────────────────────────────────────

info "Installing coturn..."
apt-get update -q
apt-get install -y coturn openssl
success "coturn installed"

# ── Generate self-signed cert if no real cert provided ────────────────────────

CERT_DIR="/etc/coturn/certs"
mkdir -p "$CERT_DIR"

if [[ -n "${TLS_CERT:-}" && -n "${TLS_KEY:-}" ]]; then
  TURN_CERT="$TLS_CERT"
  TURN_KEY="$TLS_KEY"
  success "Using provided TLS cert: $TURN_CERT"
else
  warn "No TLS_CERT/TLS_KEY provided — generating self-signed certificate."
  warn "For production, use Let's Encrypt: certbot certonly --standalone -d $TURN_DOMAIN"
  TURN_CERT="$CERT_DIR/turn.crt"
  TURN_KEY="$CERT_DIR/turn.key"
  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "$TURN_KEY" -out "$TURN_CERT" \
    -subj "/CN=$TURN_DOMAIN" 2>/dev/null
  chmod 600 "$TURN_KEY"
  success "Self-signed cert generated at $TURN_CERT"
fi

# ── Write /etc/turnserver.conf ─────────────────────────────────────────────────

CONF=/etc/turnserver.conf
info "Writing $CONF..."

cat > "$CONF" << EOF
# =============================================================================
# Coturn configuration — generated by PRaww+ coturn-setup.sh
# =============================================================================

# Listening interfaces and ports
listening-port=3478
tls-listening-port=5349

# Public IP / external IP for NAT traversal
external-ip=$PUBLIC_IP

# Realm — typically your domain
realm=$TURN_DOMAIN

# ── Authentication ────────────────────────────────────────────────────────────
# REST API / HMAC time-limited credentials (compatible with PRaww+ verto.ts)
# Username format: "<unix_timestamp>:<user_id>"
# Credential:      HMAC-SHA1(TURN_SECRET, username) → base64
#
# NOTE: use-auth-secret (REST API mode) and lt-cred-mech (long-term credentials)
# are mutually exclusive in Coturn. Do NOT add lt-cred-mech here — it disables
# the REST API auth mode and will cause all HMAC credentials to be rejected.
use-auth-secret
static-auth-secret=$TURN_SECRET

# ── TLS / DTLS ────────────────────────────────────────────────────────────────
cert=$TURN_CERT
pkey=$TURN_KEY
# Disable insecure TLS versions
no-tlsv1
no-tlsv1_1

# ── Relay port range ──────────────────────────────────────────────────────────
# Must be open in the VPS firewall (UDP $RELAY_MIN_PORT-$RELAY_MAX_PORT)
min-port=$RELAY_MIN_PORT
max-port=$RELAY_MAX_PORT

# ── Performance & security ────────────────────────────────────────────────────
# Enable fingerprints in TURN messages (required by WebRTC)
fingerprint

# Deny relay to loopback/private ranges (security hardening)
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Allow relay to any public IP
# (remove denied-peer-ip lines above if relaying to private RFC1918 is needed)

# ── Transport ─────────────────────────────────────────────────────────────────
# Enable both UDP and TCP TURN (required for full NAT traversal)
# TCP relay is critical for networks that block UDP
no-multicast-peers

# ── Logging ───────────────────────────────────────────────────────────────────
log-file=/var/log/coturn/turnserver.log
# Rotate logs
new-log-timestamp

# ── Process ───────────────────────────────────────────────────────────────────
pidfile=/run/coturn/turnserver.pid
EOF

chmod 640 "$CONF"
success "$CONF written"

# ── Enable coturn service ──────────────────────────────────────────────────────

DEFAULTS=/etc/default/coturn
info "Enabling coturn in $DEFAULTS..."
if grep -q "^#TURNSERVER_ENABLED" "$DEFAULTS" 2>/dev/null; then
  sed -i 's/^#TURNSERVER_ENABLED/TURNSERVER_ENABLED/' "$DEFAULTS"
elif ! grep -q "^TURNSERVER_ENABLED" "$DEFAULTS" 2>/dev/null; then
  echo "TURNSERVER_ENABLED=1" >> "$DEFAULTS"
fi
success "coturn enabled"

# ── Create log directory ───────────────────────────────────────────────────────

mkdir -p /var/log/coturn
chown turnserver:turnserver /var/log/coturn 2>/dev/null || true

# ── Open firewall ports ────────────────────────────────────────────────────────

info "Opening firewall ports..."
if command -v ufw &>/dev/null; then
  ufw allow 3478/tcp  comment "TURN UDP/TCP"
  ufw allow 3478/udp  comment "TURN UDP"
  ufw allow 5349/tcp  comment "TURNS TLS"
  ufw allow 5349/udp  comment "TURNS DTLS"
  ufw allow "${RELAY_MIN_PORT}:${RELAY_MAX_PORT}/udp" comment "TURN relay UDP range"
  success "ufw rules added"
else
  warn "ufw not found — add these firewall rules manually:"
  echo "  iptables -A INPUT -p tcp --dport 3478 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport 3478 -j ACCEPT"
  echo "  iptables -A INPUT -p tcp --dport 5349 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport 5349 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport ${RELAY_MIN_PORT}:${RELAY_MAX_PORT} -j ACCEPT"
fi

# ── Oracle Cloud / cloud provider security list reminder ─────────────────────
warn "If using Oracle Cloud: also open ports in the VCN Security List:"
warn "  Ingress: 3478 TCP+UDP, 5349 TCP+UDP, ${RELAY_MIN_PORT}-${RELAY_MAX_PORT} UDP"

# ── Start / restart coturn ────────────────────────────────────────────────────

info "Starting coturn service..."
systemctl daemon-reload
systemctl enable coturn
systemctl restart coturn
sleep 2

if systemctl is-active --quiet coturn; then
  success "coturn is running"
else
  error "coturn failed to start — check: journalctl -u coturn -n 50"
fi

# ── Health check ──────────────────────────────────────────────────────────────

info "Verifying TURN port 3478 is listening..."
if ss -lntu | grep -q ":3478 "; then
  success "Port 3478 is open"
else
  warn "Port 3478 not detected — coturn may still be starting, check: ss -lntu | grep 3478"
fi

# ── Print env vars to add to PRaww+ ───────────────────────────────────────────

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Coturn setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}Add these environment variables to your PRaww+ .env:${NC}"
echo ""
echo "  TURN_HOST=$TURN_DOMAIN"
echo "  TURN_SECRET=$TURN_SECRET"
echo ""
echo -e "${CYAN}ICE server configuration (auto-generated by API when env vars are set):${NC}"
echo ""
cat << ICEEOF
  [
    { "urls": "stun:${TURN_DOMAIN}:3478" },
    {
      "urls": [
        "turn:${TURN_DOMAIN}:3478?transport=udp",
        "turn:${TURN_DOMAIN}:3478?transport=tcp",
        "turns:${TURN_DOMAIN}:5349?transport=tcp"
      ],
      "username": "<generated per-request via HMAC>",
      "credential": "<generated per-request via HMAC>"
    }
  ]
ICEEOF
echo ""
echo -e "${CYAN}Verify TURN health after deployment:${NC}"
echo "  curl https://your-app/api/healthz/turn | jq ."
echo ""
echo -e "${CYAN}Check coturn logs:${NC}"
echo "  journalctl -u coturn -f"
echo "  tail -f /var/log/coturn/turnserver.log"
echo ""
echo -e "${YELLOW}Required firewall ports (check VPS security group too):${NC}"
echo "  3478  TCP + UDP   — TURN/STUN"
echo "  5349  TCP         — TURNS/TLS"
echo "  ${RELAY_MIN_PORT}–${RELAY_MAX_PORT}  UDP           — relay range"
echo ""
