#!/usr/bin/env bash
# =============================================================================
# PRaww+ — Coturn TURN/STUN Server Setup
# =============================================================================
# Run this on your Ubuntu/Debian VPS (same or separate machine from FreeSWITCH).
#
# What this script does:
#   1. Installs Coturn
#   2. Generates a strong TURN_SECRET (or uses your existing one)
#   3. Writes /etc/turnserver.conf with all required settings
#   4. Opens firewall ports (ufw)
#   5. Enables and starts the coturn systemd service
#   6. Prints the env vars to add to your PRaww+ .env
#
# Usage:
#   chmod +x deploy/coturn-setup.sh
#   sudo ./deploy/coturn-setup.sh
#
# Required env vars (set before running or the script will prompt):
#   TURN_DOMAIN   — public hostname/IP for the TURN server  e.g. turn.praww.co.za
#   TURN_SECRET   — shared HMAC secret (generated if blank)
#   PUBLIC_IP     — VPS public IP (auto-detected if blank)
#
# Optional:
#   RELAY_MIN_PORT  — relay UDP port range start  (default: 49152)
#   RELAY_MAX_PORT  — relay UDP port range end    (default: 65535)
#   TLS_CERT        — path to TLS cert PEM (e.g. /etc/letsencrypt/live/.../fullchain.pem)
#   TLS_KEY         — path to TLS key PEM  (e.g. /etc/letsencrypt/live/.../privkey.pem)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo $0"

# ── Collect required values ────────────────────────────────────────────────────

if [[ -z "${TURN_DOMAIN:-}" ]]; then
  read -rp "TURN server hostname (e.g. turn.praww.co.za or your VPS IP): " TURN_DOMAIN
fi
[[ -z "$TURN_DOMAIN" ]] && error "TURN_DOMAIN is required"

if [[ -z "${PUBLIC_IP:-}" ]]; then
  PUBLIC_IP=$(curl -sf https://api4.my-ip.io/ip 2>/dev/null || curl -sf https://ipv4.icanhazip.com 2>/dev/null || true)
  if [[ -z "$PUBLIC_IP" ]]; then
    read -rp "VPS public IP address: " PUBLIC_IP
  fi
fi
[[ -z "$PUBLIC_IP" ]] && error "PUBLIC_IP is required"

if [[ -z "${TURN_SECRET:-}" ]]; then
  TURN_SECRET=$(openssl rand -hex 32)
  info "Generated TURN_SECRET: $TURN_SECRET"
fi

RELAY_MIN_PORT=${RELAY_MIN_PORT:-49152}
RELAY_MAX_PORT=${RELAY_MAX_PORT:-65535}

echo ""
info "Configuration:"
echo "  TURN_DOMAIN   = $TURN_DOMAIN"
echo "  PUBLIC_IP     = $PUBLIC_IP"
echo "  TURN_SECRET   = [hidden]"
echo "  Relay ports   = $RELAY_MIN_PORT–$RELAY_MAX_PORT"
echo "  TLS cert      = ${TLS_CERT:-[none — TLS 5349 will use self-signed]}"
echo ""

# ── Install Coturn ─────────────────────────────────────────────────────────────

info "Installing coturn..."
apt-get update -q
apt-get install -y coturn openssl
success "coturn installed"

# ── Generate self-signed cert if no real cert provided ────────────────────────

CERT_DIR="/etc/coturn/certs"
mkdir -p "$CERT_DIR"

if [[ -n "${TLS_CERT:-}" && -n "${TLS_KEY:-}" ]]; then
  TURN_CERT="$TLS_CERT"
  TURN_KEY="$TLS_KEY"
  success "Using provided TLS cert: $TURN_CERT"
else
  warn "No TLS_CERT/TLS_KEY provided — generating self-signed certificate."
  warn "For production, use Let's Encrypt: certbot certonly --standalone -d $TURN_DOMAIN"
  TURN_CERT="$CERT_DIR/turn.crt"
  TURN_KEY="$CERT_DIR/turn.key"
  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "$TURN_KEY" -out "$TURN_CERT" \
    -subj "/CN=$TURN_DOMAIN" 2>/dev/null
  chmod 600 "$TURN_KEY"
  success "Self-signed cert generated at $TURN_CERT"
fi

# ── Write /etc/turnserver.conf ─────────────────────────────────────────────────

CONF=/etc/turnserver.conf
info "Writing $CONF..."

# Guard: if an existing config uses lt-cred-mech, warn loudly.
# lt-cred-mech and use-auth-secret are mutually exclusive in Coturn —
# having both causes Coturn to reject ALL HMAC credentials silently.
if [[ -f "$CONF" ]] && grep -q '^lt-cred-mech' "$CONF" 2>/dev/null; then
  warn "Existing $CONF contains 'lt-cred-mech' — removing it."
  warn "lt-cred-mech conflicts with use-auth-secret (REST API / HMAC mode)."
  warn "See: https://coturn.net/turnserver/#turn-rest-api-draft"
fi

cat > "$CONF" << EOF
# =============================================================================
# Coturn configuration — generated by PRaww+ coturn-setup.sh
# $(date -u)
# =============================================================================

# Listening interfaces and ports
listening-port=3478
tls-listening-port=5349

# Bind to all interfaces (Oracle/AWS: public IP is NAT'd via the NIC)
listening-ip=0.0.0.0

# Public IP / external IP for NAT traversal
external-ip=$PUBLIC_IP

# Realm — typically your domain
realm=$TURN_DOMAIN

# ── Authentication ────────────────────────────────────────────────────────────
# REST API / HMAC time-limited credentials (compatible with PRaww+ verto.ts)
# Username format: "<unix_timestamp>:<user_id>"
# Credential:      HMAC-SHA1(TURN_SECRET, username) → base64
#
# IMPORTANT: use-auth-secret (REST API mode) and lt-cred-mech (long-term
# credentials) are mutually exclusive in Coturn.  Do NOT add lt-cred-mech
# here — it disables REST API auth mode and causes all HMAC credentials to be
# rejected silently.  See: https://coturn.net/turnserver/#turn-rest-api-draft
use-auth-secret
static-auth-secret=$TURN_SECRET

# ── TLS / DTLS ────────────────────────────────────────────────────────────────
cert=$TURN_CERT
pkey=$TURN_KEY
# Disable insecure TLS versions
no-tlsv1
no-tlsv1_1

# ── Relay port range ──────────────────────────────────────────────────────────
# Must be open in the VPS firewall (UDP $RELAY_MIN_PORT-$RELAY_MAX_PORT)
min-port=$RELAY_MIN_PORT
max-port=$RELAY_MAX_PORT

# ── Performance & security ────────────────────────────────────────────────────
# Enable fingerprints in TURN messages (required by WebRTC)
fingerprint

# Deny relay to loopback/private ranges (security hardening)
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Allow relay to any public IP
# (remove denied-peer-ip lines above if relaying to private RFC1918 is needed)

# ── Transport ─────────────────────────────────────────────────────────────────
# Enable both UDP and TCP TURN (required for full NAT traversal)
# TCP relay is critical for networks that block UDP
no-multicast-peers

# ── Logging ───────────────────────────────────────────────────────────────────
log-file=/var/log/coturn/turnserver.log
# Rotate logs
new-log-timestamp

# ── Process ───────────────────────────────────────────────────────────────────
pidfile=/run/coturn/turnserver.pid
EOF

chmod 640 "$CONF"
success "$CONF written"

# ── Enable coturn service ──────────────────────────────────────────────────────

DEFAULTS=/etc/default/coturn
info "Enabling coturn in $DEFAULTS..."
if grep -q "^#TURNSERVER_ENABLED" "$DEFAULTS" 2>/dev/null; then
  sed -i 's/^#TURNSERVER_ENABLED/TURNSERVER_ENABLED/' "$DEFAULTS"
elif ! grep -q "^TURNSERVER_ENABLED" "$DEFAULTS" 2>/dev/null; then
  echo "TURNSERVER_ENABLED=1" >> "$DEFAULTS"
fi
success "coturn enabled"

# ── Create required runtime directories ───────────────────────────────────────

mkdir -p /var/log/coturn
chown turnserver:turnserver /var/log/coturn 2>/dev/null || true

# coturn writes its PID file to /run/coturn/turnserver.pid — the directory
# must exist and be owned by the turnserver user or coturn will fail to start.
mkdir -p /run/coturn
chown turnserver:turnserver /run/coturn 2>/dev/null || true

# ── Fix TLS cert permissions for coturn ───────────────────────────────────────
# Let's Encrypt certs are only readable by root by default.
# coturn (running as the 'turnserver' user) must be able to read the private key
# or port 5349 (TURNS/TLS) will silently not start.
#
# Strategy: add the turnserver user to the ssl-cert group and set group-read
# permission on the live cert directory.  certbot deploy hooks below keep this
# in place after each renewal.

if [[ -n "${TLS_CERT:-}" && "$TLS_CERT" == /etc/letsencrypt/* ]]; then
  DOMAIN_DIR=$(dirname "$(dirname "$TLS_CERT")")  # /etc/letsencrypt/live/<domain>
  info "Fixing Let's Encrypt cert permissions for coturn..."

  # Add turnserver to ssl-cert group (idempotent)
  if getent group ssl-cert &>/dev/null; then
    usermod -aG ssl-cert turnserver 2>/dev/null || true
    success "Added turnserver to ssl-cert group"
  fi

  # Ensure the live/<domain> directory and privkey are group-readable
  chmod 750 "$DOMAIN_DIR"                   2>/dev/null || true
  chmod 640 "${TLS_KEY}"                    2>/dev/null || true
  chown root:turnserver "${TLS_KEY}"        2>/dev/null || true
  chown root:turnserver "${TLS_CERT}"       2>/dev/null || true
  chmod 644 "${TLS_CERT}"                   2>/dev/null || true

  # Install certbot post-renewal hook so permissions are re-applied automatically
  HOOK_DIR="/etc/letsencrypt/renewal-hooks/deploy"
  mkdir -p "$HOOK_DIR"
  HOOK_FILE="$HOOK_DIR/coturn-restart.sh"
  cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# Certbot post-renewal hook — restores coturn cert permissions + restarts coturn
set -euo pipefail
DOMAIN_DIR="/etc/letsencrypt/live"
for DIR in "$DOMAIN_DIR"/*/; do
  KEY="$DIR/privkey.pem"
  CERT="$DIR/fullchain.pem"
  [ -f "$KEY"  ] && chown root:turnserver "$KEY"  && chmod 640 "$KEY"  || true
  [ -f "$CERT" ] && chown root:turnserver "$CERT" && chmod 644 "$CERT" || true
  chmod 750 "$DIR" || true
done
mkdir -p /run/coturn
chown turnserver:turnserver /run/coturn || true
systemctl restart coturn || true
HOOK
  chmod 755 "$HOOK_FILE"
  success "Certbot post-renewal hook installed at $HOOK_FILE"
fi

# ── Open firewall ports ────────────────────────────────────────────────────────

info "Opening firewall ports..."
if command -v ufw &>/dev/null; then
  ufw allow 3478/tcp  comment "TURN UDP/TCP"
  ufw allow 3478/udp  comment "TURN UDP"
  ufw allow 5349/tcp  comment "TURNS TLS"
  ufw allow 5349/udp  comment "TURNS DTLS"
  ufw allow "${RELAY_MIN_PORT}:${RELAY_MAX_PORT}/udp" comment "TURN relay UDP range"
  success "ufw rules added"
else
  warn "ufw not found — add these firewall rules manually:"
  echo "  iptables -A INPUT -p tcp --dport 3478 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport 3478 -j ACCEPT"
  echo "  iptables -A INPUT -p tcp --dport 5349 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport 5349 -j ACCEPT"
  echo "  iptables -A INPUT -p udp --dport ${RELAY_MIN_PORT}:${RELAY_MAX_PORT} -j ACCEPT"
fi

# ── Oracle Cloud / cloud provider security list reminder ─────────────────────
warn "If using Oracle Cloud: also open ports in the VCN Security List:"
warn "  Ingress: 3478 TCP+UDP, 5349 TCP+UDP, ${RELAY_MIN_PORT}-${RELAY_MAX_PORT} UDP"

# ── Start / restart coturn ────────────────────────────────────────────────────

info "Starting coturn service..."
systemctl daemon-reload
systemctl enable coturn
systemctl restart coturn
sleep 2

if systemctl is-active --quiet coturn; then
  success "coturn is running"
else
  error "coturn failed to start — check: journalctl -u coturn -n 50"
fi

# ── Validate listening ports ───────────────────────────────────────────────────

info "Verifying TURN ports are listening..."
sleep 2

PORT_3478_OK=false
PORT_5349_OK=false

if ss -lntu 2>/dev/null | grep -q ":3478 "; then
  success "Port 3478 is listening (TURN UDP/TCP)"
  PORT_3478_OK=true
else
  warn "Port 3478 not detected — coturn may still be starting. Check: ss -lntu | grep 3478"
fi

if ss -lntu 2>/dev/null | grep -q ":5349 "; then
  success "Port 5349 is listening (TURNS TLS)"
  PORT_5349_OK=true
else
  warn "Port 5349 not detected — TLS cert may be invalid or missing."
  warn "Fix: sudo certbot certonly --standalone -d $TURN_DOMAIN"
  warn "     Then re-run this script with TLS_CERT and TLS_KEY set."
fi

# ── Validate TLS cert paths ────────────────────────────────────────────────────

info "Validating TLS certificate..."
if [[ -f "$TURN_CERT" && -f "$TURN_KEY" ]]; then
  # Check cert expiry
  EXPIRY=$(openssl x509 -enddate -noout -in "$TURN_CERT" 2>/dev/null | cut -d= -f2 || echo "")
  if [[ -n "$EXPIRY" ]]; then
    EXPIRY_TS=$(date -d "$EXPIRY" +%s 2>/dev/null || echo "0")
    NOW_TS=$(date +%s)
    DAYS_LEFT=$(( (EXPIRY_TS - NOW_TS) / 86400 ))
    if [[ "$DAYS_LEFT" -gt 30 ]]; then
      success "TLS cert valid for $DAYS_LEFT days (expires $EXPIRY)"
    elif [[ "$DAYS_LEFT" -gt 0 ]]; then
      warn "TLS cert expires SOON — $DAYS_LEFT days ($EXPIRY)"
      warn "Renew: sudo certbot renew && sudo systemctl restart coturn"
    else
      warn "TLS cert is EXPIRED or unreadable — TURNS/5349 will not work"
      warn "Renew: sudo certbot renew --force-renewal && sudo systemctl restart coturn"
    fi
  else
    warn "Could not read TLS cert expiry from $TURN_CERT"
  fi
  # Guard: ensure lt-cred-mech is absent from the written config
  if grep -q '^lt-cred-mech' "$CONF" 2>/dev/null; then
    error "FATAL: $CONF still contains 'lt-cred-mech' after rewrite — this will break HMAC auth. Remove it and restart coturn."
  fi
else
  warn "TLS cert path $TURN_CERT or key $TURN_KEY does not exist"
fi

# ── Print env vars to add to PRaww+ ───────────────────────────────────────────

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Coturn setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}Add these environment variables to your PRaww+ .env:${NC}"
echo ""
echo "  TURN_HOST=$TURN_DOMAIN"
echo "  TURN_SECRET=$TURN_SECRET"
echo ""
echo -e "${CYAN}ICE server configuration (auto-generated by API when env vars are set):${NC}"
echo ""
cat << ICEEOF
  [
    { "urls": "stun:${TURN_DOMAIN}:3478" },
    {
      "urls": [
        "turn:${TURN_DOMAIN}:3478?transport=udp",
        "turn:${TURN_DOMAIN}:3478?transport=tcp",
        "turns:${TURN_DOMAIN}:5349?transport=tcp"
      ],
      "username": "<generated per-request via HMAC>",
      "credential": "<generated per-request via HMAC>"
    }
  ]
ICEEOF
echo ""
echo -e "${CYAN}Verify TURN health after deployment:${NC}"
echo "  curl https://your-app/api/healthz/turn | jq ."
echo ""
echo -e "${CYAN}Check coturn logs:${NC}"
echo "  journalctl -u coturn -f"
echo "  tail -f /var/log/coturn/turnserver.log"
echo ""
echo -e "${YELLOW}Required firewall ports (check VPS security group too):${NC}"
echo "  3478  TCP + UDP   — TURN/STUN"
echo "  5349  TCP         — TURNS/TLS"
echo "  ${RELAY_MIN_PORT}–${RELAY_MAX_PORT}  UDP           — relay range"
echo ""
