import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import callsRouter from "./calls";
import paymentsRouter from "./payments";
import numbersRouter from "./numbers";
import adminRouter from "./admin";
import contactsRouter from "./contacts";
import vertoRouter from "./verto";
import freeswitchRouter from "./freeswitch";
import billingRouter from "./billing";
import cdrRouter from "./cdr";
import ratePlansRouter from "./ratePlans";
import invoicesRouter from "./invoices";
import adminBillingRouter from "./adminBilling";
import voicemailRouter from "./voicemail";
import recordingsRouter from "./recordings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(callsRouter);
router.use(paymentsRouter);
router.use(numbersRouter);
router.use(adminRouter);
router.use(contactsRouter);
router.use(vertoRouter);
router.use(freeswitchRouter);
router.use(billingRouter);
router.use(cdrRouter);
router.use(ratePlansRouter);
router.use(invoicesRouter);
router.use(adminBillingRouter);
router.use(voicemailRouter);
router.use(recordingsRouter);

export default router;
