import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metricsRouter from "./metrics";
import authRouter from "./auth";
import usersRouter from "./users";
import callsRouter from "./calls";
import paymentsRouter from "./payments";
import numbersRouter from "./numbers";
import adminRouter from "./admin";
import contactsRouter from "./contacts";
import vertoRouter from "./verto";
import freeswitchRouter from "./freeswitch";
import billingRouter from "./billing";
import cdrRouter from "./cdr";
import ratePlansRouter from "./ratePlans";
import invoicesRouter from "./invoices";
import adminBillingRouter from "./adminBilling";
import voicemailRouter from "./voicemail";
import recordingsRouter from "./recordings";
import resellerRouter from "./reseller";
import announcementsRouter from "./announcements";
import callEventsRouter from "./callEvents";
import alertRulesRouter from "./alertRules";
import ipBlocksRouter from "./ipBlocks";
import auditSearchRouter from "./auditSearch";
import logLevelRouter from "./logLevel";
import tenantsRouter from "./tenants";
import conferenceRouter from "./conference";
import setupRouter from "./setup";
import adminOpsRouter from "./adminOps";
import ivrRouter from "./ivr";
import queuesRouter from "./queues";
import cdrExportRouter from "./cdrExport";
import securityRouter from "./security";
import analyticsRouter from "./analytics";
import portRequestsRouter from "./portRequests";
import resellerCommissionsRouter from "./resellerCommissions";
import callerIdProfilesRouter from "./callerIdProfiles";
import orgRouter from "./org";
import ringGroupsRouter from "./ringGroups";

const router: IRouter = Router();

router.use(setupRouter);
router.use(healthRouter);
router.use(metricsRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(callsRouter);
router.use(paymentsRouter);
router.use(numbersRouter);
router.use(adminRouter);
router.use(resellerRouter);
router.use(contactsRouter);
router.use(vertoRouter);
router.use(freeswitchRouter);
router.use(billingRouter);
router.use(cdrRouter);
router.use(ratePlansRouter);
router.use(invoicesRouter);
router.use(adminBillingRouter);
router.use(voicemailRouter);
router.use(recordingsRouter);
router.use(announcementsRouter);
router.use(callEventsRouter);
router.use(alertRulesRouter);
router.use(ipBlocksRouter);
router.use(auditSearchRouter);
router.use(logLevelRouter);
router.use(tenantsRouter);
router.use(conferenceRouter);
router.use(adminOpsRouter);
router.use(ivrRouter);
router.use(queuesRouter);
router.use(cdrExportRouter);
router.use(securityRouter);
router.use(analyticsRouter);
router.use(portRequestsRouter);
router.use(resellerCommissionsRouter);
router.use(callerIdProfilesRouter);
router.use(orgRouter);
router.use(ringGroupsRouter);

export default router;
