// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/voip-dashboard/AuroraGlass.tsx": () => import("../components/mockups/voip-dashboard/AuroraGlass.tsx"),
  "./components/mockups/voip-dashboard/DeepGlass.tsx": () => import("../components/mockups/voip-dashboard/DeepGlass.tsx"),
  "./components/mockups/voip-dashboard/PureLiquid.tsx": () => import("../components/mockups/voip-dashboard/PureLiquid.tsx")
};
