#!/usr/bin/env tsx
/**
 * scripts/deploy-vps.ts
 * Full Oracle VPS deployment via SSH.
 *
 * Reads secrets from process.env (Replit Secrets / local .env).
 * SSHes into the VPS, sets up Node.js/pnpm/PM2/nginx, clones/updates
 * the repo, writes the .env, builds the app, and starts it with PM2.
 *
 * Usage: pnpm tsx scripts/deploy-vps.ts
 */

import { Client as SSH, type ClientChannel } from "ssh2";

// ── Config read from environment ────────────────────────────────────────────
const VPS_HOST   = process.env.FREESWITCH_DOMAIN ?? "";
const SSH_USER   = process.env.FREESWITCH_SSH_USER ?? "ubuntu";
const SSH_PORT   = parseInt(process.env.FREESWITCH_SSH_PORT ?? "22");
const RAW_KEY    = process.env.FREESWITCH_SSH_KEY ?? "";

const APP_URL    = process.env.APP_URL ?? "https://rtc.praww.co.za";
const DOMAIN     = APP_URL.replace(/^https?:\/\//, "").replace(/\/$/, "");

const DEPLOY_DIR = "/home/ubuntu/PRawwPlus";
const REPO_URL   = "https://github.com/praww527/PRawwPlus.git";
const NODE_VER   = "22";
const PNPM_VER   = "10.26.1";

if (!VPS_HOST) { console.error("FREESWITCH_DOMAIN not set"); process.exit(1); }
if (!RAW_KEY)  { console.error("FREESWITCH_SSH_KEY not set"); process.exit(1); }

// ── SSH key normalisation ────────────────────────────────────────────────────
function cleanKey(raw: string): string {
  let s = raw.trim();
  if (s.includes("\\n")) s = s.replace(/\\n/g, "\n");
  if (!s.includes("\n") && s.includes("-----BEGIN") && s.includes("-----END")) {
    const hm = s.match(/(-----BEGIN [^-]+-----)/);
    const fm = s.match(/(-----END [^-]+-----)/);
    if (hm && fm) {
      const body = s.slice(s.indexOf(hm[1]) + hm[1].length, s.indexOf(fm[1])).trim().replace(/\s+/g, "\n");
      s = `${hm[1]}\n${body}\n${fm[1]}`;
    }
  }
  return s.split("\n").map(l => l.trimStart()).join("\n").trim();
}

// ── .env file content ────────────────────────────────────────────────────────
function buildDotEnv(): string {
  const e = process.env;
  const fsKey = (e.FREESWITCH_SSH_KEY ?? "").replace(/\n/g, "\\n");
  const fbKey = (e.FIREBASE_PRIVATE_KEY ?? "").replace(/\n/g, "\\n");
  return [
    "# PRaww+ production environment — generated by deploy-vps.ts",
    `PORT=3000`,
    `NODE_ENV=production`,
    `TRUST_PROXY=1`,
    `APP_URL=${e.APP_URL ?? ""}`,
    `LOG_LEVEL=info`,
    ``,
    `MONGODB_URI=${e.MONGODB_URI ?? ""}`,
    `MONGODB_USE_TRANSACTIONS=false`,
    ``,
    `FIREBASE_PROJECT_ID=${e.FIREBASE_PROJECT_ID ?? ""}`,
    `FIREBASE_CLIENT_EMAIL=${e.FIREBASE_CLIENT_EMAIL ?? ""}`,
    `FIREBASE_PRIVATE_KEY="${fbKey}"`,
    ``,
    `FREESWITCH_DOMAIN=${e.FREESWITCH_DOMAIN ?? ""}`,
    `FREESWITCH_ESL_HOST=127.0.0.1`,
    `FREESWITCH_ESL_PORT=8021`,
    `FREESWITCH_ESL_PASSWORD=${e.FREESWITCH_ESL_PASSWORD ?? ""}`,
    `FREESWITCH_WS_URL=ws://127.0.0.1:8081/`,
    `FREESWITCH_SIP_WS_URL=ws://127.0.0.1:5066`,
    `FREESWITCH_SIP_WS_PORT=5066`,
    `FREESWITCH_SSH_USER=ubuntu`,
    `FREESWITCH_SSH_PORT=22`,
    `FREESWITCH_SSH_KEY="${fsKey}"`,
    `FREESWITCH_CONF_DIR=/etc/freeswitch`,
    `FREESWITCH_STORAGE_DIR=/usr/local/freeswitch/storage`,
    `FREESWITCH_WEBHOOK_SECRET=${e.FREESWITCH_WEBHOOK_SECRET ?? ""}`,
    ``,
    `PAYFAST_MERCHANT_ID=${e.PAYFAST_MERCHANT_ID ?? ""}`,
    `PAYFAST_MERCHANT_KEY=${e.PAYFAST_MERCHANT_KEY ?? ""}`,
    `PAYFAST_PASSPHRASE=${e.PAYFAST_PASSPHRASE ?? ""}`,
    ``,
    `SMTP_HOST=${e.SMTP_HOST ?? ""}`,
    `SMTP_PORT=${e.SMTP_PORT ?? "587"}`,
    `SMTP_USER=${e.SMTP_USER ?? ""}`,
    `SMTP_PASS=${e.SMTP_PASS ?? ""}`,
    `SMTP_FROM=PRaww+ <noreply@praww.co.za>`,
    ``,
    `LOW_BALANCE_THRESHOLD_COINS=10`,
    `MAX_BILLSEC_PER_CALL=3600`,
    `MAX_COINS_SPEND_PER_DAY=500`,
    `MAX_CONCURRENT_CALLS_PER_USER=2`,
    `RECONCILIATION_INTERVAL_MS=60000`,
  ].join("\n") + "\n";
}

// ── SSH helpers ──────────────────────────────────────────────────────────────
function connect(): Promise<SSH> {
  return new Promise((resolve, reject) => {
    const conn = new SSH();
    conn.on("ready", () => resolve(conn));
    conn.on("error", reject);
    conn.connect({ host: VPS_HOST, port: SSH_PORT, username: SSH_USER, privateKey: cleanKey(RAW_KEY), readyTimeout: 20_000 });
  });
}

function exec(conn: SSH, cmd: string, label: string, showOutput = true): Promise<string> {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, (err, stream: ClientChannel) => {
      if (err) { reject(new Error(`${label}: ${err.message}`)); return; }
      let out = ""; let errOut = "";
      stream.on("data", (d: Buffer) => { out += d.toString(); });
      stream.stderr.on("data", (d: Buffer) => { errOut += d.toString(); });
      stream.on("close", (code: number) => {
        const combined = (out + "\n" + errOut).trim();
        if (code !== 0) {
          reject(new Error(`${label} failed (exit ${code}):\n${combined}`));
        } else {
          if (showOutput && out.trim()) console.log(`    ${out.trim().split("\n").join("\n    ")}`);
          resolve(out.trim());
        }
      });
    });
  });
}

function uploadFile(conn: SSH, remotePath: string, content: string): Promise<void> {
  return new Promise((resolve, reject) => {
    conn.sftp((err, sftp) => {
      if (err) { reject(err); return; }
      const stream = sftp.createWriteStream(remotePath, { mode: 0o600 });
      stream.on("close", resolve);
      stream.on("error", reject);
      stream.end(content);
    });
  });
}

// ── Main deployment ──────────────────────────────────────────────────────────
async function deploy() {
  console.log(`\n🚀  Deploying PRaww+ to ${VPS_HOST} (${DOMAIN})\n`);

  const conn = await connect();
  console.log("✅  SSH connected\n");

  try {

    // ── Step 1: System packages ─────────────────────────────────────────────
    console.log("📦  [1/9] Updating system packages...");
    await exec(conn,
      "sudo DEBIAN_FRONTEND=noninteractive apt-get update -q && " +
      "sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq git curl nginx ufw certbot python3-certbot-nginx",
      "apt-get"
    );
    console.log("✅  System packages ready\n");

    // ── Step 2: Node.js ─────────────────────────────────────────────────────
    console.log(`📦  [2/9] Installing Node.js ${NODE_VER}...`);
    await exec(conn,
      `node --version 2>/dev/null | grep -q "v${NODE_VER}" || (` +
      `curl -fsSL https://deb.nodesource.com/setup_${NODE_VER}.x | sudo -E bash - && ` +
      `sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq nodejs)`,
      "nodejs"
    );
    const nodeVer = await exec(conn, "node --version", "node-version");
    console.log(`✅  Node.js ${nodeVer}\n`);

    // ── Step 3: pnpm ────────────────────────────────────────────────────────
    console.log(`📦  [3/9] Installing pnpm ${PNPM_VER}...`);
    await exec(conn,
      `pnpm --version 2>/dev/null || (sudo npm install -g pnpm@${PNPM_VER})`,
      "pnpm"
    );
    const pnpmVer = await exec(conn, "pnpm --version", "pnpm-version");
    console.log(`✅  pnpm ${pnpmVer}\n`);

    // ── Step 4: PM2 ─────────────────────────────────────────────────────────
    console.log("📦  [4/9] Installing PM2...");
    await exec(conn,
      "pm2 --version 2>/dev/null || sudo npm install -g pm2",
      "pm2"
    );
    await exec(conn,
      "sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu 2>/dev/null | tail -1 | sudo bash || true",
      "pm2-startup"
    );
    console.log("✅  PM2 ready\n");

    // ── Step 5: Clone / update repo ─────────────────────────────────────────
    console.log("📂  [5/9] Cloning / updating repo...");
    await exec(conn,
      `if [ -d "${DEPLOY_DIR}/.git" ]; then ` +
        `git -C "${DEPLOY_DIR}" fetch origin && git -C "${DEPLOY_DIR}" reset --hard origin/master; ` +
      `else ` +
        `git clone ${REPO_URL} "${DEPLOY_DIR}"; ` +
      `fi`,
      "git-clone"
    );
    console.log("✅  Repo ready\n");

    // ── Step 6: Write .env + updated package.json ───────────────────────────
    console.log("🔐  [6/9] Writing .env to VPS...");
    const dotenv = buildDotEnv();
    await uploadFile(conn, `${DEPLOY_DIR}/.env`, dotenv);

    // Upload updated package.json (includes ignoredBuiltDependencies for ARM64)
    const { readFile } = await import("fs/promises");
    const pkgJson = await readFile(new URL("../package.json", import.meta.url), "utf-8");
    await uploadFile(conn, `${DEPLOY_DIR}/package.json`, pkgJson);
    console.log("✅  .env + package.json written\n");

    // ── Step 7: Install deps + build ────────────────────────────────────────
    console.log("🔨  [7/9] Installing dependencies and building...");
    // Remove stale node_modules and lockfile (lockfile may have wrong-arch binaries)
    await exec(conn,
      `rm -rf "${DEPLOY_DIR}/node_modules" "${DEPLOY_DIR}/pnpm-lock.yaml" 2>/dev/null; true`,
      "rm-stale-deps", false
    );
    // Fresh install — no --ignore-scripts so platform-specific optional deps resolve
    await exec(conn,
      `cd "${DEPLOY_DIR}" && CI=true pnpm install --no-frozen-lockfile 2>&1`,
      "pnpm-install"
    );
    await exec(conn,
      `cd "${DEPLOY_DIR}" && CI=true ` +
      `pnpm --filter @workspace/db run build && CI=true ` +
      `pnpm --filter @workspace/auth-web run build && CI=true ` +
      `pnpm --filter @workspace/api-client-react run build`,
      "build-libs"
    );
    await exec(conn,
      `cd "${DEPLOY_DIR}" && CI=true pnpm --filter @workspace/prawwplus run build`,
      "build-frontend"
    );
    await exec(conn,
      `cd "${DEPLOY_DIR}" && CI=true pnpm --filter @workspace/api-server run build`,
      "build-backend"
    );
    await exec(conn,
      `mkdir -p "${DEPLOY_DIR}/logs"`,
      "mkdir-logs"
    );
    console.log("✅  Build complete\n");

    // ── Step 8: Configure nginx ─────────────────────────────────────────────
    console.log("🌐  [8/9] Configuring nginx...");
    await exec(conn,
      `sudo cp "${DEPLOY_DIR}/deploy/nginx.conf" /etc/nginx/sites-available/prawwplus && ` +
      `sudo ln -sf /etc/nginx/sites-available/prawwplus /etc/nginx/sites-enabled/prawwplus && ` +
      `sudo rm -f /etc/nginx/sites-enabled/default && ` +
      `sudo nginx -t && sudo systemctl reload nginx`,
      "nginx-config"
    );
    console.log("✅  Nginx configured\n");

    // ── Step 9: Start / restart PM2 ─────────────────────────────────────────
    console.log("🟢  [9/9] Starting app with PM2...");
    await exec(conn,
      `cd "${DEPLOY_DIR}" && ` +
      `(pm2 reload ecosystem.config.cjs --update-env 2>/dev/null || ` +
       `pm2 start ecosystem.config.cjs) && ` +
      `pm2 save`,
      "pm2-start"
    );
    const pm2Status = await exec(conn, "pm2 list --no-color", "pm2-list");
    console.log(`\n${pm2Status}\n`);
    console.log("✅  App running with PM2\n");

    // ── Firewall ─────────────────────────────────────────────────────────────
    console.log("🔒  Configuring UFW firewall...");
    await exec(conn, "sudo bash -c 'ufw allow 22/tcp && ufw allow 80/tcp && ufw allow 443/tcp && ufw allow 16384:32768/udp && ufw --force enable' 2>&1 || true", "ufw");
    console.log("✅  Firewall configured\n");

    console.log("════════════════════════════════════════════════════════");
    console.log("  ✅  PRaww+ deployed to Oracle VPS");
    console.log(`  🌍  URL: https://${DOMAIN}`);
    console.log("  ⚠️   SSL: run on VPS:  sudo certbot --nginx -d " + DOMAIN);
    console.log("  📋  Logs: pm2 logs prawwplus");
    console.log("════════════════════════════════════════════════════════\n");

  } finally {
    conn.end();
  }
}

deploy().catch(err => {
  console.error("\n❌  Deployment failed:", err.message);
  process.exit(1);
});
